{% set name = "myst-nb" %}
{% set version = "0.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1eacac39805487055f534b8351d93e806a9c85c0465538311a6494b256b423c3

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - docutils >=0.15
    - importlib-metadata >=3.6
    - ipython
    - ipywidgets >=7.0.0,<8
    - jupyter-cache >=0.4.1,<0.5
    - jupyter-sphinx ~=0.3.2
    - myst-parser ~=0.13.5
    - nbconvert >=5.5,<6
    - nbformat >=5.0,<6
    - python >=3.6
    - pyyaml
    - sphinx >=2,<4
    - sphinx-togglebutton >=0.2.2,<0.3

test:
  requires:
    - pip
  imports:
    - myst_nb
    - myst_nb.nb_glue
  # reuires jupyter-cache to pin sqlalchemy
  # commands:
  #  - pip check

about:
  home: https://github.com/executablebooks/MyST-NB
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A Jupyter Notebook Sphinx reader built on top of the MyST markdown parser.
  doc_url: https://myst-nb.readthedocs.io

extra:
  recipe-maintainers:
    - chrisjsewell
