{% set name = "myst-nb" %}
{% set version = "0.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9c7ab37929da72f78569a37bcccbc5d49fd679fd7935bf6c9fa36365eb58783a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - flit-core >=3.4,<4
  run:
    - importlib-metadata
    - ipython
    - jupyter-cache ~=0.5.0
    - nbclient
    - myst-parser ~=0.18.0
    - nbformat ~=5.0
    - pyyaml
    - sphinx >=4,<6
    - sphinx-togglebutton ~=0.3.0
    - typing-extensions
    - ipykernel
    - python >=3.7

test:
  requires:
    - pip
  imports:
    - myst_nb
    - myst_nb.ext.glue
  commands:
    - pip check

about:
  home: https://github.com/executablebooks/MyST-NB
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A Jupyter Notebook Sphinx reader built on top of the MyST markdown parser.
  doc_url: https://myst-nb.readthedocs.io

extra:
  recipe-maintainers:
    - mmcky
    - conda-forge/jupyter-book
